//
// Copyright (c) 2016-2017 Contributors to the Eclipse Foundation
//
// See the NOTICE file(s) distributed with this work for additional
// information regarding copyright ownership.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// You may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// Contributors:
// Emily Jiang

[[circuitbreaker]]
== Circuit Breaker
Circuit Breaker prevents repeating timeout, so that invoking dysfunctional services or APIs fail fast.
There are three circuit states:

* Closed: the service functions well. If a failure occurs, the circuit breaker keeps the record, after the specified failures are reached, the circuit will be opened.

* Open: calls to the circuit breaker fail immediately. After the specified timeout is reached, the circuit transitions to half open state.

* Half-open: one call to the circuit is allowed. If it fails, the circuit will remain open. Otherwise, subsequent calls are allowed. After the specified successful execution, the circuit will be closed.
