//
// Copyright (c) 2016-2017 Eclipse Microprofile Contributors:
// Emily Jiang
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

[[retry]]
== Retry Policy

In order to recover from a brief network glitch, `Retry` can be used to invoke the same operation again.
The `Retry` policy allows to configure :

* `maxRetries`: the maximum retries
* `delay`: delays between each retry
* `delayUnit`: the delay unit
* `maxDuration`: maximum duration to perform the retry for.
* `durationUnit`: duration unit
* `jitter`: the random vary of retry delays
* `jitterDelayUnit`: the jitter unit
* `retryOn`: specify the failure to retry on
* `abortOn`: specify the failure to abort on

=== Retry usage

`Retry` can be applied to the class or method level.
If applied to a class, it means the all methods in the class will have the `Retry` policy applied.
If applied to a method, it means  that method will have `Retry` policy applied.
If the `Retry` policy applied on a class level and on a method level within that class, the method level `Retry` will override the class-level `Retry` policy for that particular method.

[source, java]
----
    /**
     * The configured the max retries is 90 but the max duration is 1000ms.
     * Once the duration is reached, no more retries should be performed,
     * even through it has not reached the max retries.
     */
    @Retry(maxRetries = 90, maxDuration= 1000)
    public void serviceB() {
        writingService();
    }

    /**
    * There should be 0-800ms (jitter is -400ms - 400ms) delays
    * between each invocation.
    * there should be at least 4 retries but no more than 10 retries.
    */
    @Retry(delay = 400, maxDuration= 3200, jitter= 400, maxRetries = 10)
    public Connection serviceA() {
        return connectionService();
    }

    /**
    * Sets retry condition, which means Retry will be performed on
    * IOException.
    */
    @Retry(retryOn = {IOException.class})
    public void serviceB() {
        writingService();
    }
----

The `Retry` annotation can be used together with `Fallback`, `CircuitBreaker`, `Asynchronous`, `Bulkhead` and `Timeout`.
A `Fallback` can be specified and it will be invoked if the `Retry` still fails.
If `Retry` is used together with `Timeout`, the `TimoutException` will trigger the retry.
