//
// Copyright (c) 2016-2019 Eclipse Microprofile Contributors:
// Emily Jiang
// Andrew Rouse
// Ladislav Thon
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

[[retry]]
== Retry Policy

In order to recover from a brief network glitch, `@Retry` can be used to invoke the same operation again.
The `Retry` policy allows to configure :

* `maxRetries`: the maximum retries
* `delay`: delays between each retry
* `delayUnit`: the delay unit
* `delayFactor`: the delay factor, which exponentially backs off to the maxDelay and multiplying successive delays by the delayFactor
* `maxDelay`: the maximum delay between the retries
* `maxDelayUnit`: the maximum delay unit
* `maxDuration`: maximum duration to perform the retry for.
* `durationUnit`: maximum duration unit
* `jitter`: the random vary of retry delays
* `jitterDelayUnit`: the jitter unit
* `retryOn`: specify the failures to retry on
* `abortOn`: specify the failures to abort on
The delay between the retries will be affected by `delay`, `jitter` and `delayFactor`. After applying the policies, if the delay exceeds the `maxDelay`, the value of `maxDelay` will be used.
=== Retry usage

`@Retry` can be applied to the class or method level.
If applied to a class, it means the all methods in the class will have the `@Retry` policy applied.
If applied to a method, it means  that method will have `@Retry` policy applied.
If the `@Retry` policy applied on a class level and on a method level within that class, the method level `@Retry` will override the class-level `@Retry` policy for that particular method.

When a method returns and the retry policy is present, the following rules are applied:

* If the method returns normally (doesn't throw), the result is simply returned.
* Otherwise, if the thrown object is assignable to any value in the `abortOn` parameter, the thrown object is rethrown.
* Otherwise, if the thrown object is assignable to any value in the `retryOn` parameter, the method call is retried.
* Otherwise the thrown object is rethrown.

For example, to retry on all exceptions except for IO exceptions, one would write:

[source,java]
----
    /**
     * In case the underlying service throws an exception, it will be retried,
     * unless the thrown exception was an IO exception.
     */
    @Retry(retryOn = Exception.class, abortOn = IOException.class)
    public void service() {
        underlyingService();
    }
----

If a method throws a `Throwable` which is not an `Error` or `Exception`, non-portable behavior results.

[source, java]
----
    /**
     * The configured the max retries is 90 but the max duration is 1000ms.
     * Once the duration is reached, no more retries should be performed,
     * even through it has not reached the max retries.
     */
    @Retry(maxRetries = 90, maxDuration= 1000)
    public void serviceB() {
        writingService();
    }

    /**
    * There should be 0-800ms (jitter is -400ms - 400ms) delays
    * between each invocation.
    * there should be at least 4 retries but no more than 10 retries.
    */
    @Retry(delay = 400, maxDuration= 3200, jitter= 400, maxRetries = 10)
    public Connection serviceA() {
        return connectionService();
    }

    /**
    * There should be 0-400ms delays between each invocation.
    * The effective delay will be between:
    * [delay - jitter, delay + jitter] and always >= 0. Negative effective delays will be 0.
    * There should be at least 8 retries but no more than 10 retries.
    */
    @Retry(delay = 0, maxDuration= 3200, jitter= 400, maxRetries = 10)
    public Connection serviceA() {
        return connectionService();
    }

    /**
    * Sets retry condition, which means Retry will be performed on
    * IOException.
    */
    @Retry(retryOn = {IOException.class})
    public void serviceB() {
        writingService();
    }
----

The `@Retry` annotation can be used together with `@Fallback`, `@CircuitBreaker`, `@Asynchronous`, `@Bulkhead` and `@Timeout`.

A `@Fallback` can be specified and it will be invoked if the method still fails after any retires have been run.

If `@Retry` is used with `@Asynchronous` and a retry is required, the new retry attempt may be run on the same thread as the previous attempt, or on a different thread. (However, note that if `@Retry` is used with `@Timeout` and `@Asynchronous`, and a `TimeoutException` results in a new retry attempt, the new retry attempt must start after the configured delay period, even if the previous retry attempt has not finished. See <<timeout-usage>>.)
